apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodb-operator-cluster-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    
  - apiGroups: ["org.acme"]
    resources: ["mongodbs", "mongodbs/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
