apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-operator
  template:
    metadata:
      labels:
        app: mongodb-operator
    spec:
      containers:
        - name: operator
          image: mongodb-operator:11
          imagePullPolicy: IfNotPresent
